# Configuration file required by the Controller Manager to load the specified controls.
# See https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml

controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    individual_position_controller:
      type: position_controllers/JointGroupPositionController

    robotiq_3f_status_publisher_controller:
      type: joint_state_broadcaster/JointStateBroadcaster


individual_position_controller:
  ros__parameters:
    joints:
      - finger_a
      - finger_b
      - finger_c
      - scissor