# Configuration file required by the Controller Manager to load the specified controls.
# See https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml

controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    robotiq_3f_controller:
      type: robotiq_3f_controllers/Robotiq3fController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_state_broadcaster:
  ros__parameters:
    joints:
      - finger_a_joint_1
      - finger_a_joint_2
      - finger_a_joint_3
      - finger_b_joint_1
      - finger_b_joint_2
      - finger_b_joint_3
      - finger_c_joint_1
      - finger_c_joint_2
      - finger_c_joint_3
      - palm_finger_b_joint
      - palm_finger_c_joint
